#ifndef _VTSS_VERSION_H_
#define _VTSS_VERSION_H_
#define VTSS_VERSION_MAJOR    1
#define VTSS_VERSION_MINOR    8
#define VTSS_VERSION_REVISION 395
#define VTSS_VERSION_STRING   "1.8.395-625246"
#endif
